version: "3"

services:

  webserver:
    build:
      context: ./bin/webserver
    tty: true
    container_name: webserver
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true
    env_file:
      - .env


  mysql:
    build:
      context: ./bin/mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./bin/mysql/data:/var/lib/mysql
      - ./bin/mysql/logs:/var/logs/mysql
      - ./bin/mysql/configs/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env

